name: extforge-${_BUILD_ARG_EXT_NAME}

services:
    phpext:
        container_name: extforge-${_BUILD_ARG_EXT_NAME}
        ports:
            - "${_80_PORT}:80"
        build:
            context: .
            args:
                EXT_NAME: ${_BUILD_ARG_EXT_NAME}
                PHP_VERSION: ${_BUILD_ARG_PHP_VERSION}
        volumes:
            - ${_VOLUME_EXT_HOST_PATH}:/php/${_BUILD_ARG_EXT_NAME}
            - ${_VOLUME_SERVER_HOST_PATH}:/php/server